<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>fetch using async-await</title>
  </head>
  <body>
    <script>
      //Note: study from code 38 to 40

      async function getItems() {
        const response = await fetch("https://dummyjson.com/carts");
        const result = await response.json(); //here it also returns promise therefore await here aswell
        return result;
      }
      getItems()
        .then((result) => console.log(result))
        .catch((error) => console.log("Error: ", error));

      //making it even more shorter

      const getItems1 = async () => {
        return (await fetch("https://dummyjson.com/carts")).json();
      };
      getItems1()
        .then((result) => console.log("getItems1: ", result))
        .catch((error) => console.log("Error2: ", error));

      //handling error using try and catch its better use this way
      async function getItems2() {
        try {
          return (await fetch("https://dummyjson.com/carts")).json();
        } catch (error) {
          console.log("error3: ", error);
        } finally {
          console.log("Finally is optional");
        }
      }
      getItems2().then((r) => console.log("getItems2: ", r));
      //now we don't need to write catch here everytime we call this function we can only use
      //then to get the response/result
    </script>
  </body>
</html>
